server:
  error:
    include-message: always
spring:
  application:
    name: personal-financial
  datasource:
    url: jdbc:h2:mem:personal_financial
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      settings:
        trace: false 
        web-allow-others: false

